version: '3'
services:
  apigateway:
    build:
      context: .
      dockerfile: DockerfileApiGateway
    container_name: apigateway
    ports:
      - 9876:9876
      - 8080:8080
    command: npm run start
    networks:
      - backend
networks:
  backend:
    driver: bridge
